Repository arcticicestudio/snowsaw, pull requests merged in 2019-06, with the labels that each got.

#50 Initial repository clean up for Go rewrite
  .editorconfig
  .gitignore
  .idea/misc.xml
  .idea/modules.xml
  .idea/runConfigurations/snowsaw.xml
  .idea/snowsaw.iml
  .idea/vcs.xml
  CHANGELOG.md
  README.md
  assets/icon-snowblocks.ai
  assets/icon-snowblocks.svg
  assets/scrot-readme-debugging-code.png
  assets/scrot-readme-debugging-run-configuration.png
  assets/scrot-readme-debugging-run-menu.png
  assets/scrot-readme-debugging-run.png
  assets/scrot-readme-debugging-variables.png
  assets/snowsaw-banner.ai
  assets/snowsaw-banner.svg
  assets/snowsaw-logo-banner.ai
  assets/snowsaw-logo-banner.svg
  assets/snowsaw-logo.ai
  assets/snowsaw-logo.svg
  bin/snowsaw
  snowsaw/__init__.py
  snowsaw/cli.py
  snowsaw/config.py
  snowsaw/context.py
  snowsaw/dispatcher.py
  snowsaw/logging/__init__.py
  snowsaw/logging/color.py
  snowsaw/logging/level.py
  snowsaw/logging/logger.py
  snowsaw/plugin.py
  snowsaw/plugins/clean.py
  snowsaw/plugins/link.py
  snowsaw/plugins/shell.py
  snowsaw/setup.py
  snowsaw/util/__init__.py
  snowsaw/util/compat.py
  snowsaw/util/module.py
  snowsaw/util/singleton.py
Labels: context-workflow, scope-maintainability, type-task

#51 MIT license
  LICENSE.md
Labels: context-documentation, scope-compatibility, type-task

#52 GitHub Open Source Community Standards
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
Labels: context-documentation, context-workflow, scope-maintainability, type-feature

#53 GitHub issue and pull request templates
  .github/ISSUE_TEMPLATE.md
  .github/ISSUE_TEMPLATE/bugs.md
  .github/ISSUE_TEMPLATE/enhancement.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: context-documentation, context-workflow, scope-maintainability, type-feature

#55 Prettier
  .prettierignore
  package-lock.json
  package.json
  prettier.config.js
Labels: context-workflow, scope-maintainability, status-in-review, type-feature

#56 git-crypt
  .git-crypt/.gitattributes
  .git-crypt/keys/default/0/2A4859DE12C40169C737B61412637B9743D0263D.gpg
  .git-crypt/keys/default/0/40F729E5476E46C260F8556E60C54F1519346085.gpg
  .gitattributes
Labels: context-workflow, scope-maintainability, scope-security, type-feature

#64 Update README.md: typo fix
  README.md
Labels: context-documentation, type-bug
